# Running an Agent

### Packaging the order-desk agent, watching it with Prometheus and Grafana, and putting it on a server

**The agent answers on a laptop. This packages it, counts how it's doing, draws those numbers, and then does all of it again on a server anyone can reach.**

- **The agent:** Porter, the order desk of Wickmere & Rook, an online gift shop. A customer asks about one of their orders; Porter looks it up in the shop's database and answers, and can open a return request that a member of staff then approves.
- **Where this ends:** the agent in a container, with Postgres beside it keeping the conversations, Prometheus collecting its numbers every 5 seconds and Grafana drawing them, first on this laptop and then on an AWS server at `http://<its address>:8080`.

## What we are building

| Part | what nobody can answer yet | what answers it |
|---|---|---|
| P1 · The container | does it run anywhere but this laptop's Python? | an image, `porter:1.0`, started by Compose, with Postgres beside it for the conversations |
| P2 · Prometheus | how many requests, how many failed, how slow? | three numbers the service keeps, collected every 5 seconds |
| P3 · Grafana | can you see all that at a glance? | a dashboard of three panels |
| P4 · Off the laptop | can anybody else reach it, and can you still watch it? | one EC2 instance running the same four containers, the service on port 8080 |

**The service's routes:**

| route | what it does |
|---|---|
| `GET /` | the chat page, for customers |
| `POST /v1/chat` | one question in, with the conversation's `thread_id`; the reply, the tools used and the tokens out |
| `GET /staff` | the returns desk, for staff |
| `GET /v1/returns` | every return request, and its refund once paid |
| `POST /v1/returns/{id}/approve` | a member of staff pays one request, once |
| `GET /healthz` | says it's up and can read the orders |
| `GET /metrics` | the service's numbers, for Prometheus |

## One request, start to finish

```mermaid
---
config:
  flowchart:
    wrappingWidth: 360
---
flowchart TD
    B(["a customer's browser<br/>http://…:8080"]) --> MW
    subgraph BOX["the porter container · P1, then on EC2 · P4"]
        MW["measure() · P2<br/>counts and times every request"] --> CH["POST /v1/chat"]
        CH --> AG["build_agent()<br/>the model, three tools, three limits"]
        AG --> T["build_tools()<br/>look_up_order · price_order · start_return"]
        AP["POST /v1/returns/{id}/approve<br/>approve(): one refund, once"]
    end
    T -->|"read"| DB[("online_retail.db<br/>the shop's orders, read-only")]
    T -->|"start_return writes a request"| L[("the ledger<br/>returns · refunds")]
    ST(["a member of staff<br/>/staff"]) --> AP
    AP -->|"writes the refund"| L
    AG <-->|"https + the key"| M["gpt-4.1-mini<br/>on OpenAI's API"]
    PG[("Postgres · P1<br/>the conversations")] <-->|"load · save, by thread_id"| AG
    PR[("Prometheus · P2<br/>reads /metrics every 5 s")] -.-> MW
    GF(["Grafana · P3<br/>three panels"]) -.-> PR

    classDef model fill:#e8f0fe,stroke:#4285f4,color:#174ea6
    classDef tools fill:#fef9c3,stroke:#ca8a04,color:#713f12
    classDef stored fill:#f3e8fd,stroke:#9334e6,color:#681da8
    classDef guard fill:#fce8e6,stroke:#d93025,color:#a50e0e
    classDef endpoint fill:#e6f4ea,stroke:#34a853,color:#137333
    classDef person fill:#fff3e0,stroke:#ef6c00,color:#8a3800
    class AG,M model
    class MW,CH,T,AP tools
    class DB,L,PG,PR stored
    class B,GF endpoint
    class ST person
    style BOX fill:none,stroke:#9aa0a6,color:#80868b
```

- **The agent** is the model plus three tools, built for one customer. Two tools only read the orders; `start_return` writes a *request* to the ledger.
- **The conversation is kept in Postgres,** a container of its own, under its `thread_id`: the next question that sends that id carries on from it.
- **Only a member of staff pays a refund,** through a route the agent has no tool for, and approving the same request twice pays once.
- **`measure()`** wraps every request, **Prometheus** reads the numbers it keeps, and **Grafana** draws them.

## The map

```
   AN AGENT ON A LAPTOP ─────────────────────────────────────► ON A SERVER, AND WATCHED
       │
  P0 ─►│  Setup ............ the packages, the key, one answer in this notebook
  P1 ─►│  The container .... a two-stage image, run by Compose beside Postgres; a return, approved once
  P2 ─►│  Prometheus ....... three numbers, collected every 5 seconds, on this laptop
  P3 ─►│  Grafana .......... three panels, watched while traffic runs, on this laptop
  P4 ─►│  Off the laptop ... the same four containers on one EC2 instance
       ▼
```

- **P0 needs an OpenAI API key. P1 to P3 add Docker, and run entirely on this laptop. P4 adds an AWS account.**
- **A `!` line is a command you could type in a terminal,** in this folder. The notebook runs it so the command and what it printed stay together.
- **Each Part opens with a picture.** The colours: 🟩 a caller, or a result · 🟦 the model · 🟨 code: a function, a route, a command · 🟪 stored data · 🟥 a failure · 🟧 a person.

---
# P0 · Setup

**Two things first: the packages, and an OpenAI API key in `.env`. Then the agent answers one question, here, as a plain function call.**

| new word | what it means here |
|---|---|
| agent | a model that can call tools: here, functions that read the shop's orders |
| tool | a Python function the model may ask to run, with arguments it fills in |
| `.env` | a file of `NAME=value` lines, read at start-up. The key lives there, never in the code |
| service | a program that answers requests over the network. Porter's is a FastAPI app |

In [ ]:
# The service's packages (requirements.txt), plus two this notebook uses.
%pip install -q -r requirements.txt python-dotenv ipython-autotime

In [1]:
# From here on, each cell prints how long it took.
%load_ext autotime

time: 91.6 µs (started: 2026-10-01 19:56:07 +05:30)


In [2]:
# The imports later Parts use, and the key: .env's lines become environment variables.
import os
from concurrent.futures import ThreadPoolExecutor

import httpx                                   # sends HTTP requests from Python
from dotenv import dotenv_values, load_dotenv  # reads NAME=value files: .env, deploy/.state

load_dotenv()
print("OPENAI_API_KEY", "is set" if os.getenv("OPENAI_API_KEY") else "is missing: copy .env.example to .env, then add it")

# Docker prints plain text in the cells below: no colours, and no "What's next" tips.
os.environ.update(NO_COLOR="1", DOCKER_CLI_HINTS="false")

OPENAI_API_KEY is set
time: 48.8 ms (started: 2026-10-01 19:56:07 +05:30)


### The desk

**Wickmere & Rook sells giftware online. Porter answers its customers' questions about their orders.**

- **The data** is [UCI *Online Retail*](https://archive.ics.uci.edu/dataset/352/online+retail): 541,909 real order lines from a UK gift shop, 2010–2011, in `online_retail.db`. `invoices` has one row per order (a number starting with `C` is a cancellation), `line_items` what was on each order and at what price, and `products` each product's name.
- **What it doesn't hold:** anything about shipping or delivery. Porter says so rather than guess.
- **Customer 12381** is the one followed throughout: six orders, one of them cancelled. Order 580638 came to 147.01.

### The service, as files

**`porter/` is the whole service: five small files and two pages.**

| file | what's in it |
|---|---|
| `porter/settings.py` | every setting, read from the environment: which model, where the data is, the limits |
| `porter/tools.py` | `build_tools()`: three tools bound to one customer. Two read the orders; `start_return` writes a request to the ledger |
| `porter/ledger.py` | the ledger, a small SQLite file apart from the shop's orders: return requests, and `approve()`, which turns one into a refund |
| `porter/agent.py` | `build_agent()`: the model, the tools, the rules and three limits. `open_checkpointer()`: where conversations are kept. `answer()` asks one question, in a conversation |
| `porter/api.py` | the web service: the routes, and the numbers Prometheus reads (P2) |
| `porter/web/` | the chat page (`index.html`) and the returns desk (`staff.html`) |

- **The customer is built into the tools.** `build_tools(customer_id, …)` defines the tools inside itself, so the model only fills in an order number and has no argument in which to name somebody else.
- **`build_agent()` puts limits on every run:** at most 6 model calls and 8 tool calls, and two retries of a model call that failed for a passing reason, such as a dropped connection.

In [3]:
# The agent as a plain function: one question, as customer 12381. No server yet.
from porter.agent import answer

answer("How much was order 580638?", customer_id=12381)

{'thread_id': '0f92d37568a6',
 'reply': 'Order 580638 cost a total of 147.01. It included items like cake tins, rabbit night lights, cake cases, and a cakestand.',
 'tools_used': ['price_order'],
 'input_tokens': 1030,
 'output_tokens': 49}

time: 6.48 s (started: 2026-10-01 19:56:08 +05:30)


---
# P1 · The container

```
 ▸P1◂ ── P2 ── P3 ── P4
 a two-stage image of the service, run by Compose beside Postgres on this laptop
```

**Closing:** *does it run anywhere but this laptop's Python?*

**What this Part builds: an image of `porter/`, and a container of it that answers on port 8080, with Postgres beside it keeping the conversations and the staff side working. Needs Docker running.**

| new word | what it means here |
|---|---|
| image | a packaged file system: Python, the packages and the code, built from a `Dockerfile` |
| container | a running copy of an image, kept apart from the machine around it |
| `Dockerfile` | the recipe for an image, one instruction per line |
| layer | the saved result of one instruction. If nothing above it changed, the next build reuses it |
| multi-stage build | a `Dockerfile` with two `FROM` lines: the first installs, the second ships only what the first produced |
| mount | a file from outside the container, made visible inside it. The orders arrive this way |
| volume | storage Docker keeps for a container, outside its image. The ledger lives in one |
| port mapping | `8080:8080`: this machine's port 8080 sends to the container's port 8080 |
| Compose | starts containers from a file instead of a long `docker run` line. Here three files, each one service more: `compose.app.yaml`, `compose.prometheus.yaml`, `compose.yaml` |
| `HEALTHCHECK` | a command Docker runs every 30 s to mark the container healthy or unhealthy |
| Postgres | a database server. Here it runs in a second container, beside porter, and holds the conversations |
| thread · `thread_id` | one conversation, named by an id. A question that sends the same `thread_id` carries that conversation on |
| checkpointer | where LangGraph saves a conversation between one question and the next: here, Postgres |

### P1 in one picture

```mermaid
---
config:
  flowchart:
    wrappingWidth: 360
---
flowchart TD
    F["porter/ · requirements.txt · Dockerfile"] -->|"docker build"| S1["stage 1 · build<br/>pip install into /install"]
    S1 -->|"only the installed<br/>packages cross"| IMG[("the image porter:1.0<br/>/install + porter/ · runs as user porter<br/>no orders · no key")]
    IMG -->|"docker run, with nothing else"| X{{"key: None<br/>unable to open database file"}}
    IMG -->|"docker compose -f compose.app.yaml up -d<br/>+ the orders, mounted<br/>+ the key, from .env<br/>+ /state, a volume"| C["the porter container<br/>port 8080"]
    C <-->|"the conversations,<br/>by thread_id"| PG[("the postgres container<br/>started first · its own volume")]
    C --> OK(["curl /healthz · /v1/chat<br/>200 · the answer"])
    C --> CONV(["a follow-up, the same thread_id<br/>it knows the order already"])
    C --> RET(["a return request, approved by staff<br/>one refund, even when approved twice"])

    classDef model fill:#e8f0fe,stroke:#4285f4,color:#174ea6
    classDef tools fill:#fef9c3,stroke:#ca8a04,color:#713f12
    classDef stored fill:#f3e8fd,stroke:#9334e6,color:#681da8
    classDef guard fill:#fce8e6,stroke:#d93025,color:#a50e0e
    classDef endpoint fill:#e6f4ea,stroke:#34a853,color:#137333
    classDef person fill:#fff3e0,stroke:#ef6c00,color:#8a3800
    class F,S1,C tools
    class IMG,PG stored
    class X guard
    class OK,CONV,RET endpoint
```

```
              P0: the code works here
                       │
                       ▼
                  Dockerfile
                       │
             docker build · two stages
                       │
                       ▼
                   porter:1.0
                     IMAGE
                       │
                       ▼
            run it, with nothing else
                       │
             ┌─────────┴─────────┐
             ▼                   ▼
        DB missing          key missing
             │                   │
             └─────────┬─────────┘
                       │
                   expected!
                       │
                       ▼
          hand them over at run time

          DB ───── mount ─────► container
          key ───── env ──────► container
                       │
                       ▼
   docker compose -f compose.app.yaml up -d
          postgres first, then porter
                       │
                       ▼
            curl /healthz · /v1/chat
                 200 · answered
                       │
                       ▼
    a follow-up, same thread_id: remembered
                       │
                       ▼
       a return, approved once by staff
```

### The Dockerfile

**Two stages. Open `Dockerfile` for its comments.**

```dockerfile
# --- stage 1: the dependencies
FROM python:3.12-slim AS build
WORKDIR /app
COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --prefix=/install -r requirements.txt

# --- stage 2: the image that ships
FROM python:3.12-slim
RUN useradd --create-home --uid 10001 porter
WORKDIR /app
COPY --from=build /install /usr/local
COPY porter/ ./porter/
ENV PYTHONUNBUFFERED=1 \
    PORTER_DB_PATH=/data/online_retail.db \
    PORTER_LEDGER_PATH=/state/porter_ledger.sqlite
RUN mkdir -p /data /state && chown porter:porter /state
USER porter
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/healthz')"
CMD ["uvicorn", "porter.api:app", "--host", "0.0.0.0", "--port", "8080"]
```

- **Two stages.** Stage 1 installs the packages into `/install`, with pip and its caches. Stage 2 starts again from a clean Python and copies in only `/install` and the code: nothing needed to *build* the image ships in it.
- **The packages before the code.** `requirements.txt` and its install get a layer of their own, above `COPY porter/`. Editing the code later rebuilds only the last layers; the packages come from the cache. `--mount=type=cache` also keeps pip's downloads between builds, outside the image.
- **No orders and no key inside.** `.dockerignore` keeps everything but `porter/` and `requirements.txt` out of the build. `PORTER_DB_PATH` only says where the orders will be mounted; `/state` is where the ledger will be written.
- **A user that isn't root.** A container running as root runs your agent as root. `porter` may write to `/state` and nowhere else.
- **`HEALTHCHECK` marks the container healthy or unhealthy,** from `/healthz`. It doesn't restart anything; `docker ps` shows it.
- **`--host 0.0.0.0`:** listen on every address the container has. Inside a container, `127.0.0.1` is the container itself, and nothing outside it could connect.

In [4]:
# Build the image from the Dockerfile in this folder and name it porter:1.0, then list it with its size.
# --progress plain prints each step as text, instead of a display that redraws itself.
!docker build --progress plain -t porter:1.0 .
!docker images porter

#0 building with "desktop-linux" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 2.26kB done
#1 DONE 0.0s

#2 resolve image config for docker-image://docker.io/docker/dockerfile:1


#2 ...

#3 [auth] docker/dockerfile:pull token for registry-1.docker.io
#3 DONE 0.0s



#2 resolve image config for docker-image://docker.io/docker/dockerfile:1


#2 DONE 2.1s



#4 docker-image://docker.io/docker/dockerfile:1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e
#4 resolve docker.io/docker/dockerfile:1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e done
#4 CACHED

#5 [internal] load metadata for docker.io/library/python:3.12-slim


#5 ...

#6 [auth] library/python:pull token for registry-1.docker.io
#6 DONE 0.0s



#5 [internal] load metadata for docker.io/library/python:3.12-slim


#5 DONE 1.8s



#7 [internal] load .dockerignore
#7 transferring context: 237B done
#7 DONE 0.0s

#8 [build 1/4] FROM docker.io/library/python:3.12-slim@sha256:f77ac9e44ae96ef2c90b8053ea08c31f8be030f824196b0ae4db6d462c84e51f
#8 resolve docker.io/library/python:3.12-slim@sha256:f77ac9e44ae96ef2c90b8053ea08c31f8be030f824196b0ae4db6d462c84e51f done
#8 DONE 0.0s

#9 [internal] load build context
#9 transferring context: 43.98kB done
#9 DONE 0.0s

#10 [build 2/4] WORKDIR /app
#10 CACHED

#11 [build 3/4] COPY requirements.txt .
#11 DONE 0.0s

#12 [build 4/4] RUN --mount=type=cache,target=/root/.cache/pip     pip install --prefix=/install -r requirements.txt


#12 1.165 Collecting fastapi==0.139.0 (from -r requirements.txt (line 3))


#12 1.167   Using cached fastapi-0.139.0-py3-none-any.whl.metadata (26 kB)
#12 1.239 Collecting uvicorn==0.41.0 (from -r requirements.txt (line 4))
#12 1.240   Using cached uvicorn-0.41.0-py3-none-any.whl.metadata (6.7 kB)
#12 1.401 Collecting pydantic-settings==2.13.1 (from -r requirements.txt (line 5))


#12 1.403   Using cached pydantic_settings-2.13.1-py3-none-any.whl.metadata (3.4 kB)
#12 1.495 Collecting langchain==1.2.10 (from -r requirements.txt (line 6))
#12 1.496   Using cached langchain-1.2.10-py3-none-any.whl.metadata (5.7 kB)
#12 1.589 Collecting langchain-core==1.4.8 (from -r requirements.txt (line 7))


#12 1.591   Using cached langchain_core-1.4.8-py3-none-any.whl.metadata (4.7 kB)
#12 1.660 Collecting langchain-openai==1.1.10 (from -r requirements.txt (line 8))
#12 1.661   Using cached langchain_openai-1.1.10-py3-none-any.whl.metadata (3.1 kB)
#12 1.751 Collecting langgraph==1.0.10 (from -r requirements.txt (line 9))


#12 1.752   Using cached langgraph-1.0.10-py3-none-any.whl.metadata (7.4 kB)
#12 1.808 Collecting langgraph-prebuilt==1.0.8 (from -r requirements.txt (line 10))
#12 1.809   Using cached langgraph_prebuilt-1.0.8-py3-none-any.whl.metadata (5.2 kB)
#12 1.922 Collecting langgraph-checkpoint==4.1.1 (from -r requirements.txt (line 11))


#12 1.923   Using cached langgraph_checkpoint-4.1.1-py3-none-any.whl.metadata (5.2 kB)
#12 2.007 Collecting langgraph-checkpoint-postgres==3.1.2 (from -r requirements.txt (line 12))


#12 2.240   Downloading langgraph_checkpoint_postgres-3.1.2-py3-none-any.whl.metadata (6.8 kB)


#12 2.332 Collecting psycopg==3.3.5 (from psycopg[binary]==3.3.5->-r requirements.txt (line 13))
#12 2.440   Downloading psycopg-3.3.5-py3-none-any.whl.metadata (4.3 kB)


#12 2.539 Collecting openai==2.30.0 (from -r requirements.txt (line 14))
#12 2.540   Using cached openai-2.30.0-py3-none-any.whl.metadata (29 kB)
#12 2.609 Collecting prometheus-client==0.25.0 (from -r requirements.txt (line 15))


#12 2.610   Using cached prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
#12 2.696 Collecting starlette>=0.46.0 (from fastapi==0.139.0->-r requirements.txt (line 3))
#12 2.698   Using cached starlette-1.7.0-py3-none-any.whl.metadata (6.6 kB)
#12 2.805 Collecting pydantic>=2.9.0 (from fastapi==0.139.0->-r requirements.txt (line 3))


#12 2.807   Using cached pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
#12 2.971 Collecting typing-extensions>=4.8.0 (from fastapi==0.139.0->-r requirements.txt (line 3))


#12 2.973   Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
#12 3.032 Collecting typing-inspection>=0.4.2 (from fastapi==0.139.0->-r requirements.txt (line 3))
#12 3.033   Using cached typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
#12 3.116 Collecting annotated-doc>=0.0.2 (from fastapi==0.139.0->-r requirements.txt (line 3))


#12 3.119   Using cached annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
#12 3.196 Collecting click>=7.0 (from uvicorn==0.41.0->-r requirements.txt (line 4))
#12 3.197   Using cached click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
#12 3.270 Collecting h11>=0.8 (from uvicorn==0.41.0->-r requirements.txt (line 4))


#12 3.272   Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
#12 3.351 Collecting python-dotenv>=0.21.0 (from pydantic-settings==2.13.1->-r requirements.txt (line 5))
#12 3.352   Using cached python_dotenv-1.2.4-py3-none-any.whl.metadata (29 kB)
#12 3.494 Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core==1.4.8->-r requirements.txt (line 7))


#12 3.496   Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
#12 3.561 Collecting langchain-protocol>=0.0.17 (from langchain-core==1.4.8->-r requirements.txt (line 7))
#12 3.565   Using cached langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
#12 3.669 Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core==1.4.8->-r requirements.txt (line 7))


#12 3.671   Using cached langsmith-0.14.2-py3-none-any.whl.metadata (22 kB)
#12 3.734 Collecting packaging>=23.2.0 (from langchain-core==1.4.8->-r requirements.txt (line 7))
#12 3.736   Using cached packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
#12 3.799 Collecting pyyaml<7.0.0,>=5.3.0 (from langchain-core==1.4.8->-r requirements.txt (line 7))


#12 3.801   Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl.metadata (2.4 kB)
#12 3.879 Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core==1.4.8->-r requirements.txt (line 7))
#12 3.880   Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)


#12 4.070 Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core==1.4.8->-r requirements.txt (line 7))


#12 4.071   Using cached uuid_utils-0.17.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.4 kB)
#12 4.175 Collecting tiktoken<1.0.0,>=0.7.0 (from langchain-openai==1.1.10->-r requirements.txt (line 8))


#12 4.177   Using cached tiktoken-0.14.0-cp312-cp312-manylinux_2_28_aarch64.whl.metadata (6.7 kB)
#12 4.256 Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph==1.0.10->-r requirements.txt (line 9))
#12 4.257   Using cached langgraph_sdk-0.3.15-py3-none-any.whl.metadata (1.7 kB)
#12 4.366 Collecting xxhash>=3.5.0 (from langgraph==1.0.10->-r requirements.txt (line 9))


#12 4.367   Using cached xxhash-4.0.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl.metadata (17 kB)
#12 4.459 Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint==4.1.1->-r requirements.txt (line 11))
#12 4.460   Using cached ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (3.2 kB)


#12 4.682 Collecting orjson>=3.11.5 (from langgraph-checkpoint-postgres==3.1.2->-r requirements.txt (line 12))


#12 4.683   Using cached orjson-3.12.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (41 kB)
#12 4.757 Collecting psycopg-pool>=3.2.0 (from langgraph-checkpoint-postgres==3.1.2->-r requirements.txt (line 12))
#12 4.800   Downloading psycopg_pool-3.3.3-py3-none-any.whl.metadata (2.8 kB)


#12 4.875 Collecting anyio<5,>=3.5.0 (from openai==2.30.0->-r requirements.txt (line 14))
#12 4.877   Using cached anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
#12 4.930 Collecting distro<2,>=1.7.0 (from openai==2.30.0->-r requirements.txt (line 14))


#12 4.931   Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
#12 5.073 Collecting httpx<1,>=0.23.0 (from openai==2.30.0->-r requirements.txt (line 14))


#12 5.075   Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
#12 5.170 Collecting jiter<1,>=0.10.0 (from openai==2.30.0->-r requirements.txt (line 14))
#12 5.171   Using cached jiter-0.17.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.2 kB)
#12 5.245 Collecting sniffio (from openai==2.30.0->-r requirements.txt (line 14))


#12 5.247   Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
#12 5.323 Collecting tqdm>4 (from openai==2.30.0->-r requirements.txt (line 14))
#12 5.324   Using cached tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)


#12 5.758 Collecting psycopg-binary==3.3.5 (from psycopg[binary]==3.3.5->-r requirements.txt (line 13))


#12 5.800   Downloading psycopg_binary-3.3.5-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl.metadata (2.7 kB)
#12 5.873 Collecting idna>=2.8 (from anyio<5,>=3.5.0->openai==2.30.0->-r requirements.txt (line 14))


#12 5.874   Using cached idna-3.20-py3-none-any.whl.metadata (7.2 kB)
#12 5.954 Collecting certifi (from httpx<1,>=0.23.0->openai==2.30.0->-r requirements.txt (line 14))
#12 5.956   Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)


#12 6.128 Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai==2.30.0->-r requirements.txt (line 14))


#12 6.129   Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
#12 6.197 Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain-core==1.4.8->-r requirements.txt (line 7))
#12 6.198   Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
#12 6.269 Collecting httpx2<3,>=2 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))


#12 6.270   Using cached httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
#12 6.332 Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))
#12 6.334   Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
#12 6.406 Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))


#12 6.407   Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
#12 6.519 Collecting websockets>=15.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))


#12 6.521   Using cached websockets-17.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl.metadata (6.3 kB)
#12 6.662 Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))


#12 6.663   Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata (3.3 kB)
#12 6.725 Collecting annotated-types>=0.6.0 (from pydantic>=2.9.0->fastapi==0.139.0->-r requirements.txt (line 3))
#12 6.727   Using cached annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)


#12 7.088 Collecting pydantic-core==2.46.5 (from pydantic>=2.9.0->fastapi==0.139.0->-r requirements.txt (line 3))


#12 7.090   Using cached pydantic_core-2.46.5-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.6 kB)


#12 7.374 Collecting regex (from tiktoken<1.0.0,>=0.7.0->langchain-openai==1.1.10->-r requirements.txt (line 8))


#12 7.376   Using cached regex-2026.9.29-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl.metadata (40 kB)
#12 7.450 Collecting httpcore2==2.13.1 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))
#12 7.451   Using cached httpcore2-2.13.1-py3-none-any.whl.metadata (26 kB)
#12 7.510 Collecting truststore>=0.10 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))


#12 7.511   Using cached truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
#12 7.630 Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))


#12 7.631   Using cached charset_normalizer-3.5.2-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl.metadata (46 kB)
#12 7.751 Collecting urllib3<3,>=1.26 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8->-r requirements.txt (line 7))


#12 7.752   Using cached urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
#12 7.773 Using cached fastapi-0.139.0-py3-none-any.whl (130 kB)
#12 7.774 Using cached uvicorn-0.41.0-py3-none-any.whl (68 kB)
#12 7.775 Using cached pydantic_settings-2.13.1-py3-none-any.whl (58 kB)
#12 7.777 Using cached langchain-1.2.10-py3-none-any.whl (111 kB)
#12 7.778 Using cached langchain_core-1.4.8-py3-none-any.whl (557 kB)
#12 7.779 Using cached langchain_openai-1.1.10-py3-none-any.whl (87 kB)
#12 7.780 Using cached langgraph-1.0.10-py3-none-any.whl (160 kB)
#12 7.781 Using cached langgraph_prebuilt-1.0.8-py3-none-any.whl (35 kB)
#12 7.782 Using cached langgraph_checkpoint-4.1.1-py3-none-any.whl (56 kB)
#12 7.840 Downloading langgraph_checkpoint_postgres-3.1.2-py3-none-any.whl (52 kB)
#12 7.942 Downloading psycopg-3.3.5-py3-none-any.whl (213 kB)


#12 8.110 Using cached openai-2.30.0-py3-none-any.whl (1.1 MB)


#12 8.112 Using cached prometheus_client-0.25.0-py3-none-any.whl (64 kB)
#12 8.243 Downloading psycopg_binary-3.3.5-cp312-cp312-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl (6.8 MB)


#12 10.09    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 3.8 MB/s eta 0:00:00


#12 10.09 Using cached annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
#12 10.09 Using cached anyio-4.15.1-py3-none-any.whl (132 kB)
#12 10.09 Using cached click-8.5.0-py3-none-any.whl (125 kB)
#12 10.09 Using cached distro-1.9.0-py3-none-any.whl (20 kB)
#12 10.10 Using cached h11-0.16.0-py3-none-any.whl (37 kB)
#12 10.10 Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
#12 10.10 Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
#12 10.10 Using cached jiter-0.17.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (341 kB)
#12 10.10 Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
#12 10.10 Using cached langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
#12 10.10 Using cached langgraph_sdk-0.3.15-py3-none-any.whl (98 kB)
#12 10.10 Using cached langsmith-0.14.2-py3-none-any.whl (813 kB)
#12 10.11 Using cached orjson-3.12.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (130 kB)
#12 10.11 Using cached ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_aarch64

014_aarch64.whl (203 kB)
#12 10.11 Using cached packaging-26.3-py3-none-any.whl (129 kB)
#12 10.16 Downloading psycopg_pool-3.3.3-py3-none-any.whl (40 kB)
#12 10.16 Using cached pydantic-2.13.5-py3-none-any.whl (472 kB)
#12 10.17 Using cached pydantic_core-2.46.5-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.0 MB)
#12 10.17 Using cached python_dotenv-1.2.4-py3-none-any.whl (23 kB)
#12 10.17 Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl (775 kB)
#12 10.17 Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
#12 10.17 Using cached starlette-1.7.0-py3-none-any.whl (78 kB)
#12 10.17 Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
#12 10.18 Using cached tiktoken-0.14.0-cp312-cp312-manylinux_2_28_aarch64.whl (1.2 MB)
#12 10.18 Using cached tqdm-4.70.1-py3-none-any.whl (80 kB)
#12 10.18 Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
#12 10.18 Using cached typing_inspection-0.4.4-py3-none-any.

#12 10.19 Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
#12 10.19 Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
#12 10.19 Using cached websockets-17.1-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl (225 kB)
#12 10.20 Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.whl (5.1 MB)
#12 10.20 Using cached regex-2026.9.29-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl (805 kB)
#12 10.20 Using cached charset_normalizer-3.5.2-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl (246 kB)
#12 10.20 Using cached truststore-0.10.4-py3-none-any.whl (18 kB)
#12 10.20 Using cached urllib3-2.8.0-py3-none-any.whl (135 kB)
#12 10.28 Installing collected packages: zstandard, xxhash, websockets, uuid-utils, urllib3, typing-extensions, truststore, tqdm, tenacity, sniffio, regex, pyyaml, python-dotenv, psycopg-binary, prometheus-client,

#12 12.58 Successfully installed annotated-doc-0.0.5 annotated-types-0.8.0 anyio-4.15.1 certifi-2026.7.22 charset_normalizer-3.5.2 click-8.5.0 distro-1.9.0 fastapi-0.139.0 h11-0.16.0 httpcore-1.0.9 httpcore2-2.13.1 httpx-0.28.1 httpx2-2.13.1 idna-3.20 jiter-0.17.0 jsonpatch-1.33 jsonpointer-3.1.1 langchain-1.2.10 langchain-core-1.4.8 langchain-openai-1.1.10 langchain-protocol-0.0.19 langgraph-1.0.10 langgraph-checkpoint-4.1.1 langgraph-checkpoint-postgres-3.1.2 langgraph-prebuilt-1.0.8 langgraph-sdk-0.3.15 langsmith-0.14.2 openai-2.30.0 orjson-3.12.0 ormsgpack-1.12.2 packaging-26.3 prometheus-client-0.25.0 psycopg-3.3.5 psycopg-binary-3.3.5 psycopg-pool-3.3.3 pydantic-2.13.5 pydantic-core-2.46.5 pydantic-settings-2.13.1 python-dotenv-1.2.4 pyyaml-6.0.3 regex-2026.9.29 requests-2.34.2 requests-toolbelt-1.0.0 sniffio-1.3.1 starlette-1.7.0 tenacity-9.1.4 tiktoken-0.14.0 tqdm-4.70.1 truststore-0.10.4 typing-extensions-4.16.0 typing-inspection-0.4.4 urllib3-2.8.0 uuid-utils-0.17.1 uvicorn-0

#12 12.58 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#12 12.59 
#12 12.59 [notice] A new release of pip is available: 25.0.1 -> 26.2.1
#12 12.59 [notice] To update, run: pip install --upgrade pip


#12 DONE 12.8s



#13 [stage-1 2/6] RUN useradd --create-home --uid 10001 porter
#13 CACHED

#14 [stage-1 3/6] WORKDIR /app
#14 CACHED

#15 [stage-1 4/6] COPY --from=build /install /usr/local


#15 DONE 0.3s



#16 [stage-1 5/6] COPY porter/ ./porter/
#16 DONE 0.0s

#17 [stage-1 6/6] RUN mkdir -p /data /state && chown porter:porter /state
#17 DONE 0.1s



#18 exporting to image
#18 exporting layers


#18 exporting layers 2.2s done
#18 exporting manifest sha256:95cf7ead26c42f4de697b5a823e3845bbd93a7e723eb0526844c3e02445a5c85


#18 exporting manifest sha256:95cf7ead26c42f4de697b5a823e3845bbd93a7e723eb0526844c3e02445a5c85 done
#18 exporting config sha256:b3c016bc60e672e3f09e6740d71dde7d21dd945b208fcb5a503be025f224735b done
#18 exporting attestation manifest sha256:38e321957b7bbdc8248f9b0ce7ff450d77ddc1f5287707617e380a711926e2ba done
#18 exporting manifest list sha256:a82716bb1be4e9d7f25ca88b2ad51168e1a3143082ab25738ebcc1a326e3ffeb done
#18 naming to docker.io/library/porter:1.0 done
#18 unpacking to docker.io/library/porter:1.0


#18 unpacking to docker.io/library/porter:1.0 0.5s done


#18 DONE 2.8s

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/xnfb4ucjwg5fdlhj4qua27e5t


                                                               Info ->  U In Use
IMAGE        ID             DISK USAGE   CONTENT SIZE   EXTRA
porter:1.0   a82716bb1be4        366MB         75.6MB        


time: 21 s (started: 2026-10-01 19:56:14 +05:30)


- **Run the cell again and the build takes seconds:** every step says `CACHED`, because nothing it depends on changed.

### The incident: the image, run with nothing else

**Run it the way a fresh machine would: the image and nothing else.** The command prints the key, then calls the service's own health check.

In [5]:
# The image on its own: no key passed, no database mounted. --rm removes the container when it exits.
!docker run --rm porter:1.0 python -c "import os; print('key:', os.getenv('OPENAI_API_KEY')); from porter.api import healthz; healthz()"

key: None


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/porter/api.py", line 83, in healthz
    con = read_only(settings.db_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/porter/tools.py", line 17, in read_only
    return sqlite3.connect(f"file:{db_path}?mode=ro", uri=True, check_same_thread=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file


time: 1.48 s (started: 2026-10-01 19:56:35 +05:30)


### Diagnosis

**Both are missing, and both on purpose: the image carries code, not data and not secrets.**

- **`key: None`.** A key built into an image is in every copy of it, forever. It's handed to the container when it starts.
- **`unable to open database file`.** The orders are 34 MB of data that change on their own schedule. They're mounted into the container, read-only, at the path `PORTER_DB_PATH` names.

### The fix: Compose hands both over

**`compose.app.yaml` says how to run the containers, porter and the Postgres beside it, so nobody has to remember a long command.** The whole file, without its comments:

```yaml
services:
  porter:
    build: .
    image: porter:1.0
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      PORTER_POSTGRES_DSN: postgresql://porter:porter@postgres:5432/porter
    volumes:
      - ./online_retail.db:/data/online_retail.db:ro
      - state:/state
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: porter
      POSTGRES_PASSWORD: porter
      POSTGRES_DB: porter
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-U", "porter"]
      interval: 2s
      retries: 15
    restart: unless-stopped

volumes:
  state:
    name: porter-state
    driver: local
  pgdata:
    name: porter-pgdata
    driver: local
```

- **`ports`:** this machine's port 8080 sends to the container's.
- **`env_file: .env`:** every line of `.env`, the key included, becomes an environment variable inside the container when it starts.
- **`environment`:** one more variable, written in the file: `PORTER_POSTGRES_DSN`, the address of the conversations. Its host, `postgres`, is the other service's name: Compose puts both containers on one network, where each finds the other by name.
- **`volumes`:** the database file, mounted read-only (`:ro`) where `PORTER_DB_PATH` says, and `state` at `/state`, where the ledger is written.
- **`postgres`:** the official Postgres image. The three `POSTGRES_` variables create its user, password and database the first time it starts. It publishes no port, so only the containers in this file can reach it.
- **`depends_on` with `service_healthy`:** porter starts only once Postgres passes its `healthcheck`: `pg_isready`, every 2 seconds, asks whether it accepts connections yet. Without the condition, porter could start first and fail to connect.
- **Two named volumes, `porter-state` and `porter-pgdata`:** storage Docker keeps on this machine's disk, outside every container, so the ledger and the conversations survive a new container. `docker volume ls` lists them; only `docker compose down -v` deletes them.
- **`restart: unless-stopped`:** if the process ever exits, Docker starts it again.
- **Three Compose files, each one service more:** this one, `compose.prometheus.yaml` in P2, and `compose.yaml` in P3. `-f` names the file; `-d` runs the containers in the background.
- **`docker compose ps`, `logs`, `stop` and `down` need no `-f`:** with none, Compose reads `compose.yaml`, which names all four services, so those commands work at every step.

In [6]:
# Step 1: start what compose.app.yaml describes, in the background: Postgres, then Porter once Postgres is healthy. --progress quiet: only errors, no progress bars.
!docker compose -f compose.app.yaml --progress quiet up -d

time: 3.11 s (started: 2026-10-01 19:56:37 +05:30)


In [7]:
# What is running, then the health check. Nothing printed? It's still starting: run the cell again.
!docker compose ps
!curl -s localhost:8080/healthz

NAME            IMAGE                COMMAND                  SERVICE    CREATED         STATUS                            PORTS
v2-porter-1     porter:1.0           "uvicorn porter.api:…"   porter     5 seconds ago   Up 2 seconds (health: starting)   0.0.0.0:8080->8080/tcp, [::]:8080->8080/tcp
v2-postgres-1   postgres:16-alpine   "docker-entrypoint.s…"   postgres   5 seconds ago   Up 5 seconds (healthy)            5432/tcp


{"status":"ok","model":"gpt-4.1-mini","api_key":"set"}

time: 530 ms (started: 2026-10-01 19:56:42 +05:30)


In [8]:
# One question, the way any program sends it: an HTTP POST with a JSON body.
!curl -s localhost:8080/v1/chat -H 'content-type: application/json' -d '{"question": "How much was order 580638?", "customer_id": 12381}'

{"thread_id":"7ab783758529","reply":"Order 580638 cost a total of 147.01. It included postage and various cake tins, cake cases, rabbit night lights, and a cakestand.","tools_used":["price_order"],"input_tokens":1030,"output_tokens":50}

time: 2.83 s (started: 2026-10-01 19:56:42 +05:30)


In [9]:
# The service's own log: one line per request, with its status code.
!docker compose logs --tail 5 porter

porter-1  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
porter-1  | INFO:     192.168.65.1:62155 - "GET /healthz HTTP/1.1" 200 OK
porter-1  | INFO:     192.168.65.1:40826 - "GET /healthz HTTP/1.1" 200 OK
porter-1  | INFO:     127.0.0.1:60416 - "GET /healthz HTTP/1.1" 200 OK
porter-1  | INFO:     192.168.65.1:40603 - "POST /v1/chat HTTP/1.1" 200 OK


time: 300 ms (started: 2026-10-01 19:56:45 +05:30)


### A conversation, kept in Postgres

**The answer above came back with a `thread_id`. A question that sends the same `thread_id` carries that conversation on, so a follow-up can say "it".**

- **`answer()` hands the `thread_id` to the agent,** which loads what was said under it, adds the new question, and saves the conversation again after every step. The saving is LangGraph's checkpointer: here a `PostgresSaver`, which `open_checkpointer()` in `porter/agent.py` opens once, when the service starts.
- **The conversation's key is `customer:thread_id`,** so another customer sending the same id starts a conversation of their own.
- **No `thread_id`:** a new conversation, with a new id. An id the caller chooses works too: the two questions below use `demo`.

In [10]:
# A question in the conversation "demo".
!curl -s localhost:8080/v1/chat -H 'content-type: application/json' -d '{"question": "When did I place order 574694?", "customer_id": 12381, "thread_id": "demo"}'

{"thread_id":"demo","reply":"You placed order 574694 on November 6, 2011. Let me know if you want to know anything else about it.","tools_used":["look_up_order"],"input_tokens":947,"output_tokens":46}

time: 2.13 s (started: 2026-10-01 19:56:46 +05:30)


In [11]:
# The same thread_id again. The question only says "it": Porter knows which order from the turn before.
!curl -s localhost:8080/v1/chat -H 'content-type: application/json' -d '{"question": "How much was it?", "customer_id": 12381, "thread_id": "demo"}'

{"thread_id":"demo","reply":"The total for order 574694 was 419.06. If you want details on any specific items, just ask.","tools_used":["price_order"],"input_tokens":1344,"output_tokens":42}

time: 2.4 s (started: 2026-10-01 19:56:48 +05:30)


In [12]:
# Where the conversations are: checkpoints, a table PostgresSaver made, one row per step saved. psql is Postgres's command line, run inside its container.
!docker compose exec postgres psql -U porter -c "SELECT thread_id, count(*) AS steps_saved FROM checkpoints GROUP BY thread_id"

     thread_id      | steps_saved 
--------------------+-------------
 12381:7ab783758529 |          11
 12381:demo         |          22
(2 rows)



time: 334 ms (started: 2026-10-01 19:56:50 +05:30)


- **`12381:demo`** is the conversation above. Any other row is a question that sent no `thread_id`, such as the first one, in a conversation of its own.
- **The conversations are in Postgres, on the `porter-pgdata` volume, not in the porter container:** a new porter container, from a new image or a restart, carries every one of them on.
- **Open <http://localhost:8080> in a browser:** the chat page, served by the container. It sends the same `POST /v1/chat`, with the `thread_id` of its first reply on every later question; reloading the page starts a new conversation.

### The staff side: a return, approved once

**The agent can only open a return *request*. A member of staff pays it, through a route the agent has no tool for, and approving it twice pays once.**

- `GET /v1/returns` lists the requests. `POST /v1/returns/{id}/approve?staff=alice` pays one: `approve()` in `porter/ledger.py` writes the refund and marks the request approved in one transaction, and a `UNIQUE` column refuses a second refund for the same request.
- There is no sign-in, so the caller names the member of staff, the way the chat names the customer.

In [13]:
# A customer asks to send an order back: the agent calls start_return, which writes a pending request.
!curl -s localhost:8080/v1/chat -H 'content-type: application/json' -d '{"question": "Order 574694 arrived broken. Please open a return for it.", "customer_id": 12381}'

{"thread_id":"f4f6e3a5b7da","reply":"I've opened a return request for order 574694 because it arrived broken. A colleague will need to approve it before any refund is issued.","tools_used":["start_return"],"input_tokens":950,"output_tokens":51}

time: 2.66 s (started: 2026-10-01 19:56:50 +05:30)


In [14]:
# The return requests, as staff see them.
!curl -s localhost:8080/v1/returns

[{"return_id":"R-28DB63A2","idempotency_key":"auto:0d780239-3047-4400-987e-5f24704cdd5c","invoice_no":"574694","customer_id":12381.0,"amount":419.06,"reason":"Order arrived broken","status":"pending","requested_at":"2026-10-01T14:26:52+00:00","decided_by":null,"decided_at":null,"refund_id":null,"paid_at":null}]

time: 229 ms (started: 2026-10-01 19:56:53 +05:30)


In [15]:
# Staff approve the newest request: a refund is written.
return_id = httpx.get("http://localhost:8080/v1/returns").json()[-1]["return_id"]
!curl -s -X POST "localhost:8080/v1/returns/$return_id/approve?staff=alice"

{"refund_id":"F-968250BF","return_id":"R-28DB63A2","invoice_no":"574694","customer_id":12381.0,"amount":419.06,"approved_by":"alice","paid_at":"2026-10-01T14:26:53+00:00","replayed":false}

time: 246 ms (started: 2026-10-01 19:56:53 +05:30)


In [16]:
# The same approval again, as a double-click or a retry would send it: the same refund, and "replayed": true.
!curl -s -X POST "localhost:8080/v1/returns/$return_id/approve?staff=alice"

{"refund_id":"F-968250BF","return_id":"R-28DB63A2","invoice_no":"574694","customer_id":12381.0,"amount":419.06,"approved_by":"alice","paid_at":"2026-10-01T14:26:53+00:00","replayed":true}

time: 229 ms (started: 2026-10-01 19:56:54 +05:30)


- **Open <http://localhost:8080/staff>:** the returns desk, with an Approve button on every pending request. It calls the same two routes.

**☑ Does it run anywhere but this laptop's Python?**

---
# P2 · Prometheus

```
 P1 ── ▸P2◂ ── P3 ── P4
       three numbers in the service, collected every 5 seconds, on this laptop
```

**Closing:** *how many requests, how many failed, how slow?*

**What this Part builds: three numbers the service keeps about every request, and Prometheus, beside the porter container, collecting them every 5 seconds.**

| new word | what it means here |
|---|---|
| metric | a number about all requests, not one: how many, how slow |
| counter | a metric that only goes up: requests answered, tokens spent. Back to 0 when the process restarts |
| histogram · bucket | requests counted per band of latency: under 1 s, under 2 s, under 3 s… |
| label | a name=value pair that splits a metric: `route="/v1/chat"`, `status="200"` |
| middleware | code that runs around every request, on its way in and on its way out |
| scrape | Prometheus reading `/metrics` over HTTP, every 5 seconds here |
| PromQL | Prometheus's query language. `rate()` turns a counter into a rate per second |
| p95 | the time 95 requests in 100 beat: what the slowest customers wait |

### P2 in one picture

```mermaid
---
config:
  flowchart:
    wrappingWidth: 360
---
flowchart TD
    R(["every request"]) --> MW["measure(), the middleware in api.py<br/>counts it · times it"]
    MW --> N[("three numbers<br/>porter_requests_total · porter_request_seconds · porter_tokens_total")]
    N -->|"GET /metrics, as text"| PR[("Prometheus, a container beside porter<br/>reads it every 5 s · keeps the history")]
    PR -->|"localhost:9090"| Q(["you, in PromQL<br/>rate() · histogram_quantile()"])

    classDef model fill:#e8f0fe,stroke:#4285f4,color:#174ea6
    classDef tools fill:#fef9c3,stroke:#ca8a04,color:#713f12
    classDef stored fill:#f3e8fd,stroke:#9334e6,color:#681da8
    classDef guard fill:#fce8e6,stroke:#d93025,color:#a50e0e
    classDef endpoint fill:#e6f4ea,stroke:#34a853,color:#137333
    classDef person fill:#fff3e0,stroke:#ef6c00,color:#8a3800
    class MW tools
    class N,PR stored
    class R,Q endpoint
```

### The numbers, in `porter/api.py`

**Three metrics, and a middleware that updates two of them around every request.** The lines that matter:

```python
REQUESTS = Counter("porter_requests_total", "Requests answered, by route and status code.", ["route", "status"])
LATENCY = Histogram("porter_request_seconds", "Seconds to answer, by route.", ["route"],
                    buckets=[0.1, 0.5, 1, 2, 3, 5, 8, 13, 21, 34, 60])
TOKENS = Counter("porter_tokens_total", "Model tokens, input and output.", ["kind"])

@app.middleware("http")
async def measure(request: Request, call_next):
    start, status = time.perf_counter(), 500
    try:
        response = await call_next(request)
        status = response.status_code
        return response
    finally:
        route = request.scope["route"].path if "route" in request.scope else "other"
        REQUESTS.labels(route, status).inc()
        LATENCY.labels(route).observe(time.perf_counter() - start)

@app.get("/metrics")
def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)
```

and in `chat()`, after each answer:

```python
TOKENS.labels("input").inc(result["input_tokens"])
TOKENS.labels("output").inc(result["output_tokens"])
```

- **`measure()` wraps every request.** `call_next` runs the route; then, whatever happened, `finally` counts the request with its status code and records how long it took. A request that crashes still counts, as a 500.
- **The label is the route that matched, never the URL itself:** `/v1/returns/{return_id}/approve`, not one label per return id. A URL that matches no route counts as `other`, so the bots that try paths such as `/wp-login.php` on any public server can't add a series each.
- **The buckets are set around this service's latencies:** an answer takes 2 to 4 seconds. The library's default buckets stop at 10 s.
- **`/metrics` prints every number as text.** That page is all Prometheus ever reads.

### Prometheus, beside the service

**It reads `/metrics` every 5 seconds, stores every line with the time, and answers questions about that history.** `compose.prometheus.yaml` is `compose.app.yaml` with Prometheus added, and Prometheus has a file of its own:

```yaml
# compose.prometheus.yaml: porter and postgres, exactly as before, and
prometheus:
  image: prom/prometheus:v3.15.0
  ports:
    - "127.0.0.1:9090:9090"
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

# prometheus.yml
global:
  scrape_interval: 5s
scrape_configs:
  - job_name: porter
    static_configs:
      - targets: ["porter:8080"]
```

- **Porter and Postgres keep running.** Their part of the file is the same as in `compose.app.yaml`, so Compose leaves their containers as they are and only adds Prometheus.
- **`porter:8080` is the service's name in the Compose file,** the way porter reaches `postgres`: the containers are on one network, where each finds the others by name.
- **`127.0.0.1:9090` publishes the port on this machine's own address only:** nothing else on the network can reach it.

In [17]:
# Step 2: start what compose.prometheus.yaml describes. Porter and Postgres are unchanged, so only Prometheus starts. Then list what is running.
!docker compose -f compose.prometheus.yaml --progress quiet up -d
!docker compose ps

NAME              IMAGE                     COMMAND                  SERVICE      CREATED          STATUS                    PORTS
v2-porter-1       porter:1.0                "uvicorn porter.api:…"   porter       18 seconds ago   Up 15 seconds (healthy)   0.0.0.0:8080->8080/tcp, [::]:8080->8080/tcp
v2-postgres-1     postgres:16-alpine        "docker-entrypoint.s…"   postgres     18 seconds ago   Up 18 seconds (healthy)   5432/tcp
v2-prometheus-1   prom/prometheus:v3.15.0   "/bin/prometheus --c…"   prometheus   1 second ago     Up Less than a second     127.0.0.1:9090->9090/tcp


time: 1.21 s (started: 2026-10-01 19:56:54 +05:30)


- **Open <http://localhost:9090/targets>:** one target, `porter`, with the state **UP** once the first scrape has run.

In [18]:
# Twenty questions, four at a time, so there's something to count. URL is the service on this laptop; P4 points it at the server.
URL = "http://localhost:8080"
QUESTIONS = ["How much was order 580638?", "When did I place order 574694?",
             "Where is my order 570681?", "What's the capital of France?"]

def ask(question):
    """One question to the service at URL, as customer 12381: its status code."""
    return httpx.post(f"{URL}/v1/chat", json={"question": question, "customer_id": 12381}, timeout=60).status_code

with ThreadPoolExecutor(max_workers=4) as pool:            # four callers at once
    print(list(pool.map(ask, QUESTIONS * 5)))

[200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200]
time: 9.89 s (started: 2026-10-01 19:57:03 +05:30)


In [19]:
# What the service's /metrics says about /v1/chat: the requests by status, the buckets, the count and the sum.
!curl -s localhost:8080/metrics | grep 'route="/v1/chat"'

porter_requests_total{route="/v1/chat",status="200"} 24.0
porter_request_seconds_bucket{le="0.1",route="/v1/chat"} 0.0
porter_request_seconds_bucket{le="0.5",route="/v1/chat"} 0.0
porter_request_seconds_bucket{le="1.0",route="/v1/chat"} 3.0
porter_request_seconds_bucket{le="2.0",route="/v1/chat"} 11.0
porter_request_seconds_bucket{le="3.0",route="/v1/chat"} 24.0
porter_request_seconds_bucket{le="5.0",route="/v1/chat"} 24.0
porter_request_seconds_bucket{le="8.0",route="/v1/chat"} 24.0
porter_request_seconds_bucket{le="13.0",route="/v1/chat"} 24.0
porter_request_seconds_bucket{le="21.0",route="/v1/chat"} 24.0
porter_request_seconds_bucket{le="34.0",route="/v1/chat"} 24.0
porter_request_seconds_bucket{le="60.0",route="/v1/chat"} 24.0
porter_request_seconds_bucket{le="+Inf",route="/v1/chat"} 24.0
porter_request_seconds_count{route="/v1/chat"} 24.0
porter_request_seconds_sum{route="/v1/chat"} 46.427179188


time: 236 ms (started: 2026-10-01 19:57:13 +05:30)


In [20]:
# And the tokens.
!curl -s localhost:8080/metrics | grep porter_tokens

# HELP porter_tokens_total Model tokens, input and output.
# TYPE porter_tokens_total counter
porter_tokens_total{kind="input"} 21061.0
porter_tokens_total{kind="output"} 1037.0


time: 232 ms (started: 2026-10-01 19:57:13 +05:30)


**Reading it:**

- **`porter_requests_total{route="/v1/chat",status="200"}`** counts every answer so far: one line per status code.
- **The buckets are cumulative.** `le="3.0"` counts every request that took 3 s or less, so each line includes the ones before it, and `le="+Inf"` counts them all. `_sum` divided by `_count` is the mean.
- **These are totals since the container started.** "How many a second, right now?" and "how slow, over the last minute?" need two readings and the time between them. That's Prometheus's job.

### Questions, in PromQL

**Paste each one into <http://localhost:9090/query>, press Execute, and open the Graph tab.** Run the twenty questions again to watch the lines move.

| question | PromQL |
|---|---|
| is the service up? (1 = the last scrape worked) | `up{job="porter"}` |
| answers since it started, by status | `sum by (status) (porter_requests_total{route="/v1/chat"})` |
| requests a second, right now | `sum(rate(porter_requests_total{route="/v1/chat"}[1m]))` |
| p95, over the last minute | `histogram_quantile(0.95, sum by (le) (rate(porter_request_seconds_bucket{route="/v1/chat"}[1m])))` |
| tokens a minute: the bill | `sum(rate(porter_tokens_total[1m])) * 60` |

- **`rate(…[1m])`** is how fast a counter grew over the last minute, per second. A restart puts the counter back to 0; `rate()` treats that as a reset, not a fall.
- **`sum by (status)`** adds the series up, keeping one per status code.
- **`histogram_quantile(0.95, …)`** estimates the 95th percentile from the buckets: it finds the bucket the 95th request in 100 falls in, and assumes the requests inside it are spread evenly.

In [21]:
# Prometheus answers over HTTP too: requests a second by status code, over the last 5 minutes (the twenty questions are inside that window).
!curl -s -G localhost:9090/api/v1/query --data-urlencode 'query=sum by (status) (rate(porter_requests_total{route="/v1/chat"}[5m]))'

{"status":"success","data":{"resultType":"vector","result":[{"metric":{"status":"200"},"value":[1790864846.300,"0.08378666666666666"]}]}}

time: 233 ms (started: 2026-10-01 19:57:26 +05:30)


**☑ How many requests, how many failed, how slow?**

---
# P3 · Grafana

```
 P1 ── P2 ── ▸P3◂ ── P4
             three panels, watched while traffic runs, on this laptop
```

**Closing:** *can you see all that at a glance?*

**What this Part builds: a dashboard of three panels, each one a PromQL query from P2 drawn over time, in Grafana beside Prometheus.**

| new word | what it means here |
|---|---|
| dashboard · panel | a page of graphs; each panel draws one PromQL query over time |
| data source | where Grafana gets its numbers: here, Prometheus |
| provisioning | Grafana reading its data source and dashboards from files when it starts, instead of someone clicking them together |

### P3 in one picture

```mermaid
---
config:
  flowchart:
    wrappingWidth: 360
---
flowchart TD
    F["grafana/<br/>datasources/prometheus.yml · dashboards/porter.json"] -->|"read when Grafana starts"| GF["Grafana, a container beside Prometheus<br/>localhost:3000"]
    PR[("Prometheus · P2")] --> GF
    T["a minute of traffic<br/>100 questions, four at a time"] --> S["the porter container"]
    S -->|"/metrics every 5 s"| PR
    GF --> P(["three panels<br/>requests a second · p95 · tokens a minute"])

    classDef model fill:#e8f0fe,stroke:#4285f4,color:#174ea6
    classDef tools fill:#fef9c3,stroke:#ca8a04,color:#713f12
    classDef stored fill:#f3e8fd,stroke:#9334e6,color:#681da8
    classDef guard fill:#fce8e6,stroke:#d93025,color:#a50e0e
    classDef endpoint fill:#e6f4ea,stroke:#34a853,color:#137333
    classDef person fill:#fff3e0,stroke:#ef6c00,color:#8a3800
    class F,GF,T,S tools
    class PR stored
    class P endpoint
```

### Grafana, beside Prometheus

**`compose.yaml` is `compose.prometheus.yaml` with Grafana added.** Its part:

```yaml
# compose.yaml: porter, postgres and prometheus, exactly as before, and
grafana:
  image: grafana/grafana:13.2.2
  ports:
    - "127.0.0.1:3000:3000"
  environment:
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/porter.json
  volumes:
    - ./grafana:/etc/grafana/provisioning:ro
```

- **`GF_AUTH_ANONYMOUS_ENABLED`:** no login page; anyone who reaches Grafana can look. Its port, like Prometheus's, is on this machine's own address only.
- **`GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH`:** the "Porter" dashboard is the page Grafana opens on.
- **`./grafana` is mounted where Grafana looks for its provisioning files,** read-only.

### The dashboard is files

**Grafana reads `grafana/` when it starts: where the numbers are, and what to draw.**

```yaml
# grafana/datasources/prometheus.yml
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
```

| panel | PromQL |
|---|---|
| Requests per second, by status | `sum by (status) (rate(porter_requests_total{route="/v1/chat"}[1m]))` |
| Latency, p95 | `histogram_quantile(0.95, sum by (le) (rate(porter_request_seconds_bucket{route="/v1/chat"}[1m])))` |
| Tokens per minute | `sum(rate(porter_tokens_total[1m])) * 60` |

- `grafana/dashboards/porter.json` holds the three panels, and `porter.yml` beside it tells Grafana to load it.
- **A dashboard in a file comes back the same on every machine,** and no stray click can change it.

In [22]:
# Step 3: start what compose.yaml describes. Porter, Postgres and Prometheus are unchanged, so only Grafana starts. Then list what is running.
!docker compose --progress quiet up -d
!docker compose ps

NAME              IMAGE                     COMMAND                  SERVICE      CREATED          STATUS                    PORTS
v2-grafana-1      grafana/grafana:13.2.2    "/run.sh"                grafana      1 second ago     Up Less than a second     127.0.0.1:3000->3000/tcp
v2-porter-1       porter:1.0                "uvicorn porter.api:…"   porter       50 seconds ago   Up 47 seconds (healthy)   0.0.0.0:8080->8080/tcp, [::]:8080->8080/tcp
v2-postgres-1     postgres:16-alpine        "docker-entrypoint.s…"   postgres     50 seconds ago   Up 50 seconds (healthy)   5432/tcp
v2-prometheus-1   prom/prometheus:v3.15.0   "/bin/prometheus --c…"   prometheus   33 seconds ago   Up 32 seconds             127.0.0.1:9090->9090/tcp


time: 1.16 s (started: 2026-10-01 19:57:26 +05:30)


In [23]:
# The dashboards Grafana loaded from grafana/, from its own HTTP API. Nothing printed? It's still starting: run the cell again.
!curl -s 'localhost:3000/api/search?query=Porter'

[{"id":2484890096017408,"uid":"porter","orgId":1,"title":"Porter","uri":"db/porter","url":"/d/porter/porter","slug":"","type":"dash-db","tags":[],"isStarred":false,"sortMeta":0,"isDeleted":false}]

time: 253 ms (started: 2026-10-01 19:57:31 +05:30)


- **Open <http://localhost:3000>:** the "Porter" dashboard is the home page, refreshing every 5 seconds.

In [24]:
# A minute of traffic: 100 questions, four at a time. Watch the dashboard while it runs.
with ThreadPoolExecutor(max_workers=4) as pool:
    codes = list(pool.map(ask, QUESTIONS * 25))
print({code: codes.count(code) for code in set(codes)})      # how many of each status code

{200: 100}
time: 46.4 s (started: 2026-10-01 19:57:32 +05:30)


**What to look for:**

- **Requests per second** climb to one or two while it runs, then fall back to nothing: one line per status code, all `200`.
- **p95** stays around 2 to 4 seconds. That's the time the model takes; four callers at once don't slow anyone down.
- **Tokens per minute** climb with the requests. Every request is paid for, whoever sends it.

**☑ Can you see all that at a glance?**

---
# P4 · Off the laptop

```
 P1 ── P2 ── P3 ── ▸P4◂
                   the same four containers on one EC2 instance, the service on port 8080
```

**Closing:** *can anybody else reach it, and can you still watch it?*

**What this Part builds: one virtual machine on AWS running the same `compose.yaml`, with port 8080 open to the internet, and Prometheus and Grafana beside the service there. Needs an AWS account, with `aws configure` done on this laptop.**

| new word | what it means here |
|---|---|
| EC2 instance | a virtual machine rented from AWS, by the hour |
| security group | the instance's firewall: which ports are open, and to whom |
| key pair | the instance's lock and key for ssh. AWS keeps the lock; the key is a file on this laptop |
| ssh | an encrypted login to another machine. The deploy scripts use it to copy files and run commands |
| public IP | the instance's address on the internet |
| ssh tunnel | a port on this laptop, carried inside an ssh connection to a port on the server |

### P4 in one picture

```mermaid
---
config:
  flowchart:
    wrappingWidth: 360
---
flowchart TD
    C1["./deploy/create.sh<br/>a key pair · a security group · a t4g.small"] --> EC2["the EC2 instance<br/>Docker installed at first boot"]
    C2["./deploy/push.sh<br/>copy the folder up, over ssh<br/>docker compose up -d --build, there"] --> EC2
    EC2 --> SVC["porter on port 8080, postgres beside it<br/>prometheus and grafana, on 127.0.0.1 only"]
    B(["a browser, anywhere<br/>http://IP:8080"]) -->|"security group: 8080 open"| SVC
    TUN["./deploy/tunnel.sh<br/>localhost:9090 and :3000 on this laptop"] -->|"ssh, port 22"| SVC
    SVC <-->|"https + the key"| M["gpt-4.1-mini"]

    classDef model fill:#e8f0fe,stroke:#4285f4,color:#174ea6
    classDef tools fill:#fef9c3,stroke:#ca8a04,color:#713f12
    classDef stored fill:#f3e8fd,stroke:#9334e6,color:#681da8
    classDef guard fill:#fce8e6,stroke:#d93025,color:#a50e0e
    classDef endpoint fill:#e6f4ea,stroke:#34a853,color:#137333
    classDef person fill:#fff3e0,stroke:#ef6c00,color:#8a3800
    class M model
    class C1,C2,EC2,SVC,TUN tools
    class B endpoint
```

### Where each piece runs

```
  a browser, anywhere ──http──► the EC2 instance, port 8080
                                ┌─────────────────────────────────────────────────────────┐
                                │ porter       the agent, from porter:1.0, built here     │
                                │   ├─► online_retail.db       copied up, read-only       │
                                │   └─► the ledger             the state volume           │
                                │ postgres     the conversations, on the pgdata volume    │
                                │ prometheus   127.0.0.1:9090  reads porter's /metrics    │
                                │ grafana      127.0.0.1:3000  draws what Prometheus kept │
                                └────────────────────────────┬────────────────────────────┘
                                                             │ https + the key
                                                             ▼
                                                 api.openai.com · gpt-4.1-mini

  this laptop ──ssh, port 22──► push.sh copies and starts it; tunnel.sh reaches 9090 and 3000
```

- **The same four containers as on the laptop,** from the same `compose.yaml`, built and started on the instance.
- **Only two doors are open:** 8080 to everyone, and 22 (ssh) to this laptop alone.

### 1 · An instance

**`deploy/create.sh` makes three things in your AWS account and writes their ids to `deploy/.state`.**

- **A key pair:** the private key goes to `~/.ssh/porter-demo.pem`; it's the only way in by ssh.
- **A security group:** port 22 from this laptop's address only, port 8080 from anywhere. Nothing else gets in, Prometheus's and Grafana's ports included.
- **A `t4g.small` instance** (2 vCPUs, 2 GB, arm64) running Ubuntu 24.04. `deploy/user_data.sh` installs Docker on its first boot.
- It costs about two US cents an hour, until `./deploy/destroy.sh`.

In [ ]:
# Make the instance. Safe to run again: it reuses whatever already exists.
!./deploy/create.sh

### 2 · The service on it

**`deploy/push.sh` copies the service up, then runs the same Compose command as the laptop, on the instance.**

- It waits until Docker is installed, then copies `porter/`, the `Dockerfile`, `compose.yaml`, the monitoring files, the database and `.env`, over ssh.
- **The key travels inside the ssh connection,** into the instance's copy of `.env`. Compose hands it to the container; the image never holds it.
- **The image is built on the instance,** from the same two-stage `Dockerfile`, and all four services start: porter, Postgres, Prometheus and Grafana.
- Run it again after any change: it copies what changed, rebuilds and restarts.

In [ ]:
# Copy, build on the instance, start. The first time, it waits a few minutes for Docker to be installed.
!./deploy/push.sh

### 3 · From outside

**Every check from here goes from this laptop, across the internet, the way a customer's browser would.**

In [ ]:
# The server's address, from the file create.sh wrote. Also an environment variable, so a `!` line can say $SERVER.
SERVER = "http://" + dotenv_values("deploy/.state")["PUBLIC_IP"] + ":8080"
os.environ["SERVER"] = SERVER
print(SERVER)

In [ ]:
# The health check, across the internet.
!curl -s $SERVER/healthz

In [ ]:
# A question, across the internet.
!curl -s $SERVER/v1/chat -H 'content-type: application/json' -d '{"question": "When did I place order 574694?", "customer_id": 12381}'

- **Open the address printed above in a browser, on a phone too:** the same chat page, from the instance, and the returns desk at `/staff`.

### 4 · Watching it there

**Prometheus and Grafana run on the instance too, listening on its own address only. An ssh tunnel brings them to this laptop, at the same two addresses as before.**

- The laptop's own Prometheus and Grafana hold those two ports, so they stop first.

In [ ]:
# Free ports 9090 and 3000 for the tunnel: stop the laptop's Prometheus and Grafana.
!docker compose --progress quiet stop prometheus grafana
!docker compose ps

In a terminal, in this folder, and leave it running:

```bash
./deploy/tunnel.sh       # the server's Prometheus on http://localhost:9090, its Grafana on http://localhost:3000
```

In [ ]:
# Twenty questions to the server this time. Then open http://localhost:3000: the server's dashboard.
URL = SERVER
with ThreadPoolExecutor(max_workers=4) as pool:
    print(list(pool.map(ask, QUESTIONS * 5)))

- **What this leaves out, on purpose:** plain `http`, which anyone on the way can read (a real site uses `https`); no sign-in, so whoever calls names the customer, or the member of staff approving a refund, and every question spends the key's money; `/metrics`, readable by anyone; and Postgres's password, `porter`, written in the Compose files, though only the containers beside it can reach it. Each one is a shortcut for a demonstration.

**☑ Can anybody else reach it, and can you still watch it?**

---
# What you can now answer

| | question | how | where |
|---|---|---|---|
| ☑ | does it run anywhere but this laptop's Python? | a two-stage image with no data and no key inside; Compose hands both over, and runs Postgres beside it for the conversations | P1 |
| ☑ | how many requests, how many failed, how slow? | three metrics in `api.py`, read by Prometheus every 5 s | P2 |
| ☑ | can you see all that at a glance? | a dashboard of three panels, from files | P3 |
| ☑ | can anybody else reach it, and can you still watch it? | one EC2 instance, the same `compose.yaml`, port 8080 open, the rest through a tunnel | P4 |

### When you're finished

```bash
./deploy/destroy.sh        # the instance and its disk, the security group, the key pair: the cost stops
docker compose down        # the containers on this laptop
```

- Close the tunnel with Ctrl+C.

### References

- [Dockerfile reference](https://docs.docker.com/reference/dockerfile/) · [multi-stage builds](https://docs.docker.com/build/building/multi-stage/) · [Compose file reference](https://docs.docker.com/reference/compose-file/) · [startup order in Compose](https://docs.docker.com/compose/how-tos/startup-order/) · [EC2 security groups](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html)
- [LangGraph persistence: threads and checkpointers](https://docs.langchain.com/oss/python/langgraph/persistence) · [the Postgres image](https://hub.docker.com/_/postgres)
- [Prometheus metric types](https://prometheus.io/docs/concepts/metric_types/) · [PromQL functions](https://prometheus.io/docs/prometheus/latest/querying/functions/) · [the Python client](https://prometheus.github.io/client_python/) · [Grafana provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/)

*Dataset: UCI Online Retail — Chen, D. (2012), [archive.ics.uci.edu/dataset/352](https://archive.ics.uci.edu/dataset/352/online+retail), CC BY 4.0.*